//! `--out <TOOL>`: export the models already configured in config.yaml into
//! another tool's config file: litellm | opencode | codex.

use crate::config::Config;
use anyhow::{bail, Context, Result};
use std::path::PathBuf;

struct ExportModel {
    client: String,
    model: String,
    api_base: String,
    api_key: Option<String>,
}

fn collect_models(config: &crate::config::Config) -> Vec<ExportModel> {
    use crate::client::{ClientConfig, OpenAICompatibleClient};
    let mut out = vec![];
    for c in &config.clients {
        if let ClientConfig::OpenAICompatibleConfig(cfg) = c {
            let client = cfg
                .name
                .clone()
                .unwrap_or_else(|| OpenAICompatibleClient::NAME.to_string());
            let base = cfg.api_base.clone().unwrap_or_default();
            let key = cfg.api_key.clone();
            for m in &cfg.models {
                out.push(ExportModel {
                    client: client.clone(),
                    model: m.name.clone(),
                    api_base: base.clone(),
                    api_key: key.clone(),
                });
            }
        }
    }
    out
}

/// --out <TOOL>: detect the tool's config file and merge in every model from
/// config.yaml (existing entries are left untouched, duplicates skipped).
pub async fn export(config: &crate::config::Config, tool: &str) -> Result<()> {
    let models = collect_models(&config);
    if models.is_empty() {
        bail!("No models configured in config.yaml. Run 'achat --init' or 'achat --add' first.");
    }
    match tool.to_lowercase().as_str() {
        "litellm" => export_litellm(&models),
        "opencode" => export_opencode(&models),
        "codex" => export_codex(&models),
        other => bail!("Unknown tool '{other}'. Supported: litellm | opencode | codex"),
    }
}

fn backup(path: &std::path::Path) -> Result<()> {
    if path.exists() {
        let bak = path.with_extension("bak");
        std::fs::copy(path, &bak)
            .with_context(|| format!("Failed to back up '{}' to '{}'", path.display(), bak.display()))?;
        println!("  (backup written to {})", bak.display());
    }
    Ok(())
}

// ------------------------------- litellm ----------------------------------

/// litellm config.yaml:
///   model_list:
///     - model_name: <alias>
///       litellm_params:
///         model: openai/<model>
///         api_base: <base>
///         api_key: <key>
fn litellm_config_path() -> PathBuf {
    // 1) LITELLM_CONFIG_PATH env, 2) ./litellm.config.yaml, 3) ~/litellm/config.yaml
    if let Ok(p) = std::env::var("LITELLM_CONFIG_PATH") {
        return PathBuf::from(p);
    }
    let cwd = std::env::current_dir().unwrap_or_default();
    for name in ["litellm.config.yaml", "config.yaml"] {
        let p = cwd.join(name);
        if p.exists() && looks_like_litellm(&p) {
            return p;
        }
    }
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("litellm/config.yaml")
}

fn looks_like_litellm(p: &std::path::Path) -> bool {
    std::fs::read_to_string(p)
        .map(|c| c.contains("model_list:") || c.contains("litellm_settings:"))
        .unwrap_or(false)
}

fn export_litellm(models: &[ExportModel]) -> Result<()> {
    let path = litellm_config_path();
    println!("litellm config: {}", path.display());
    if !path.exists() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).ok();
        }
        std::fs::write(&path, "# generated by achat --out litellm\nmodel_list:\n")?;
    }
    backup(&path)?;
    let content = std::fs::read_to_string(&path)?;

    let mut added = 0usize;
    let mut block = String::new();
    for m in models {
        // dedupe: skip if this model_name + api_base already present
        let marker = format!("model_name: {}", m.model);
        if content.contains(&marker) && content.contains(&m.api_base) {
            continue;
        }
        block.push_str(&format!(
            "  - model_name: {model}\n    litellm_params:\n      model: openai/{model}\n      api_base: {base}\n",
            model = m.model,
            base = m.api_base
        ));
        if let Some(k) = &m.api_key {
            block.push_str(&format!("      api_key: \"{k}\"\n"));
        } else {
            block.push_str("      api_key: null\n");
        }
        added += 1;
    }

    if added == 0 {
        println!("✓ litellm: no new models to add ({} checked)", models.len());
        return Ok(());
    }
    let mut new_content = content.clone();
    if content.contains("model_list:") {
        new_content = new_content.replacen("model_list:", &format!("model_list:\n{}", block.trim_end()), 1);
    } else {
        new_content.push_str(&format!("\nmodel_list:\n{}", block.trim_end()));
    }
    std::fs::write(&path, &new_content)
        .with_context(|| format!("Failed to write '{}'", path.display()))?;
    println!("✓ Added {added} models to litellm config:");
    for m in models {
        println!("  + {} (openai/{}, {})", m.model, m.model, m.client);
    }
    Ok(())
}

// ------------------------------- opencode ---------------------------------

/// opencode config (opencode.json):
///   { "provider": { "<client>": { "npm": "@ai-sdk/openai-compatible",
///       "name": <client>, "options": {"baseURL": ..., "apiKey": ...},
///       "models": { "<model>": {"name": "<model>"} } } } }
fn opencode_config_path() -> PathBuf {
    if let Ok(p) = std::env::var("OPENCODE_CONFIG") {
        return PathBuf::from(p);
    }
    let home = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));
    let p = home.join(".config/opencode/opencode.json");
    if p.exists() {
        return p;
    }
    let cwd = std::env::current_dir().unwrap_or_default();
    if cwd.join("opencode.json").exists() {
        return cwd.join("opencode.json");
    }
    p
}

fn export_opencode(models: &[ExportModel]) -> Result<()> {
    let path = opencode_config_path();
    println!("opencode config: {}", path.display());
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    backup(&path)?;
    let mut root: serde_json::Value = if path.exists() {
        let raw = std::fs::read_to_string(&path)?;
        // tolerate jsonc comments by stripping // lines
        let stripped: String = raw
            .lines()
            .map(|l| {
                let t = l.trim_start();
                if t.starts_with("//") {
                    ""
                } else {
                    l
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
        serde_json::from_str(&stripped)
            .with_context(|| format!("Failed to parse '{}'", path.display()))?
    } else {
        serde_json::json!({"$schema": "https://opencode.ai/config.json"})
    };

    let providers = root
        .as_object_mut()
        .context("opencode config root is not an object")?
        .entry("provider")
        .or_insert_with(|| serde_json::json!({}));
    let providers = providers
        .as_object_mut()
        .context("'provider' is not an object")?;

    let mut added = 0usize;
    for m in models {
        let entry = providers
            .entry(m.client.clone())
            .or_insert_with(|| serde_json::json!({}));
        let entry = entry
            .as_object_mut()
            .context("provider entry is not an object")?;
        entry.insert("npm".into(), serde_json::json!("@ai-sdk/openai-compatible"));
        entry.insert("name".into(), serde_json::json!(m.client));
        let options = entry
            .entry("options")
            .or_insert_with(|| serde_json::json!({}));
        let options = options.as_object_mut().context("options is not an object")?;
        options.insert("baseURL".into(), serde_json::json!(m.api_base));
        if let Some(k) = &m.api_key {
            options.insert("apiKey".into(), serde_json::json!(k));
        }
        let model_list = entry
            .entry("models")
            .or_insert_with(|| serde_json::json!({}));
        let model_list = model_list.as_object_mut().context("models is not an object")?;
        if model_list.contains_key(&m.model) {
            continue;
        }
        model_list.insert(
            m.model.clone(),
            serde_json::json!({ "name": m.model }),
        );
        added += 1;
    }

    std::fs::write(&path, serde_json::to_string_pretty(&root)? + "\n")
        .with_context(|| format!("Failed to write '{}'", path.display()))?;
    if added == 0 {
        println!("✓ opencode: no new models to add ({} checked)", models.len());
    } else {
        println!("✓ Added {added} models to opencode config:");
        for m in models {
            println!("  + {}.{} ({})", m.client, m.model, m.api_base);
        }
    }
    Ok(())
}

// -------------------------------- codex -----------------------------------

/// codex config (~/.codex/config.toml):
///   model_provider = "<client>"
///   [model_providers.<client>]
///   name = "<client>"
///   base_url = "<base>"
///   env_key = "..."   (we cannot write the secret; achat writes the api key
///                      only if the file does not define it — we skip keys and
///                      note them, or write experimental_bearer_token when the
///                      provider is new and the key exists)
/// Codex needs a model_provider entry per client; models are selected with
/// `codex --model <model>` or `model = "<model>"`.
fn codex_config_path() -> PathBuf {
    if let Ok(p) = std::env::var("CODEX_HOME") {
        return PathBuf::from(p).join("config.toml");
    }
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".codex/config.toml")
}

fn export_codex(models: &[ExportModel]) -> Result<()> {
    let path = codex_config_path();
    println!("codex config: {}", path.display());
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    backup(&path)?;
    let existing = if path.exists() {
        std::fs::read_to_string(&path)?
    } else {
        String::new()
    };
    let mut content = existing.clone();

    let clients: std::collections::BTreeSet<&str> =
        models.iter().map(|m| m.client.as_str()).collect();
    let mut added_providers = 0usize;
    let mut added_models = 0usize;
    let mut provider_lines = String::new();
    let mut model_lines = String::new();
    let mut key_notes = vec![];
    for client in &clients {
        let section = format!("[model_providers.{client}]");
        if content.contains(&section) {
            continue;
        }
        let m = models.iter().find(|m| &m.client == client).unwrap();
        provider_lines.push_str(&format!(
            "\n{section}\nname = \"{client}\"\nbase_url = \"{base}\"\nwire_api = \"chat\"\n",
            client = client,
            base = m.api_base
        ));
        if let Some(k) = &m.api_key {
            let env_key = format!(
                "ACHAT_{}_API_KEY",
                client.to_uppercase().replace(['-', '.'], "_")
            );
            provider_lines.push_str(&format!("env_key = \"{env_key}\"\n"));
            key_notes.push(format!("  export {}='{}'   # {}", env_key, k, client));
        }
        added_providers += 1;
    }
    for m in models {
        let marker = format!("# achat-export: {}:{}", m.client, m.model);
        if content.contains(&marker) || content.contains(&format!("model = \"{}\"", m.model)) {
            continue;
        }
        model_lines.push_str(&format!("{marker}\n# model = \"{}\"  # model_provider = \"{}\"\n", m.model, m.client));
        added_models += 1;
    }
    if !provider_lines.is_empty() {
        content.push_str("\n# --- added by achat --out codex ---\n");
        content.push_str(&provider_lines);
    }
    if !model_lines.is_empty() {
        content.push_str("\n# available models (uncomment one to set as default):\n");
        content.push_str(&model_lines);
    }
    if content != existing {
        std::fs::write(&path, &content)
            .with_context(|| format!("Failed to write '{}'", path.display()))?;
    }
    println!("✓ codex: {added_providers} providers added, {added_models} model entries noted");
    for m in models {
        println!("  + {}.{} ({})", m.client, m.model, m.api_base);
    }
    if !key_notes.is_empty() {
        println!("\nAPI keys are read from environment variables (not stored in config.toml):");
        for n in &key_notes {
            println!("{n}");
        }
    }
    Ok(())
}
